export type SceneType = "title" | "pain" | "emphasis" | "circle";
export type XiaomoPose = "peek" | "sit" | "point" | "circle" | "think" | "celebrate";
export type HighlightColor = "cyan" | "gold" | "red" | "white";

export interface BaseSceneData {
  start: number; // Start time in seconds
  end: number; // End time in seconds
  type: SceneType;
  xiaomo?: XiaomoPose;
}

export interface TitleSceneData extends BaseSceneData {
  type: "title";
  title: string;
}

export interface PainSceneData extends BaseSceneData {
  type: "pain";
  title: string;
  subtitle: string;
  number?: string;
  highlight?: string;
  highlightColor?: HighlightColor;
}

export interface EmphasisSceneData extends BaseSceneData {
  type: "emphasis";
  text: string;
}

export interface CircleSceneData extends BaseSceneData {
  type: "circle";
  text: string;
  circleTarget: string;
}

export type SceneData = TitleSceneData | PainSceneData | EmphasisSceneData | CircleSceneData;

// Example scenes data - this would be generated by the scene orchestrator
export const scenes: SceneData[] = [
  {
    start: 0.0,
    end: 3.5,
    type: "title",
    title: "三家巨头\n同一天",
    xiaomo: "peek",
  },
  {
    start: 3.5,
    end: 8.0,
    type: "pain",
    title: "微软说",
    subtitle: "Copilot 已经能写掉\n90% 的代码",
    number: "90%",
    highlight: "Copilot",
    highlightColor: "cyan",
    xiaomo: "point",
  },
  {
    start: 8.0,
    end: 12.0,
    type: "emphasis",
    text: "这世界变化太快了",
    xiaomo: "think",
  },
  {
    start: 12.0,
    end: 15.0,
    type: "circle",
    text: "程序员还在\n努力写代码",
    circleTarget: "程序员",
    xiaomo: "circle",
  },
];

export default scenes;
